---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOS)
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
      tags: always

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      tags: always

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:
    - name: copy default html file for site
      tags: apache, apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: install apache and php for Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
      tags:
        - apache
        - ubuntu

    - name: install apache and php for CentOS servers
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"
      tags:
        - apache
        - centos
        - httpd

    - name: start httpd (CentOS)
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "CentOS"
      tags:
        - apache
        - centos
        - httpd

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (CentOS)
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"
      tags:
        - centos
        - db
        - mariadb

    - name: "Mariadb - Restarting/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true
      tags:
        - db
        - mariadb

    - name: install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
      tags:
        - db
        - mariadb
        - ubuntu

- hosts: file_server
  become: true
  tasks:
    - name: install samba package
      package:
        name: samba
        state: latest
      tags:
        - samba
   - name: install mariadb package (CentOS)
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"
      tags:
        - centos
        - db
        - mariadb

    - name: "Mariadb - Restarting/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true
      tags:
        - db
        - mariadb

    - name: install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
      tags:
        - db
        - mariadb
        - ubuntu
